# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body19(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, customer_id: str=None, reference: str=None):  # noqa: E501
        """Body19 - a model defined in Swagger

        :param token: The token of this Body19.  # noqa: E501
        :type token: str
        :param customer_id: The customer_id of this Body19.  # noqa: E501
        :type customer_id: str
        :param reference: The reference of this Body19.  # noqa: E501
        :type reference: str
        """
        self.swagger_types = {
            'token': str,
            'customer_id': str,
            'reference': str
        }

        self.attribute_map = {
            'token': 'token',
            'customer_id': 'customer_id',
            'reference': 'reference'
        }
        self._token = token
        self._customer_id = customer_id
        self._reference = reference

    @classmethod
    def from_dict(cls, dikt) -> 'Body19':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_19 of this Body19.  # noqa: E501
        :rtype: Body19
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body19.


        :return: The token of this Body19.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body19.


        :param token: The token of this Body19.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def customer_id(self) -> str:
        """Gets the customer_id of this Body19.


        :return: The customer_id of this Body19.
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: str):
        """Sets the customer_id of this Body19.


        :param customer_id: The customer_id of this Body19.
        :type customer_id: str
        """

        self._customer_id = customer_id

    @property
    def reference(self) -> str:
        """Gets the reference of this Body19.


        :return: The reference of this Body19.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Body19.


        :param reference: The reference of this Body19.
        :type reference: str
        """

        self._reference = reference
