# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body20(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, reference: str=None, customer_id: str=None, session_id: str=None, payment_id: str=None):  # noqa: E501
        """Body20 - a model defined in Swagger

        :param token: The token of this Body20.  # noqa: E501
        :type token: str
        :param reference: The reference of this Body20.  # noqa: E501
        :type reference: str
        :param customer_id: The customer_id of this Body20.  # noqa: E501
        :type customer_id: str
        :param session_id: The session_id of this Body20.  # noqa: E501
        :type session_id: str
        :param payment_id: The payment_id of this Body20.  # noqa: E501
        :type payment_id: str
        """
        self.swagger_types = {
            'token': str,
            'reference': str,
            'customer_id': str,
            'session_id': str,
            'payment_id': str
        }

        self.attribute_map = {
            'token': 'token',
            'reference': 'reference',
            'customer_id': 'customer_id',
            'session_id': 'session_id',
            'payment_id': 'payment_id'
        }
        self._token = token
        self._reference = reference
        self._customer_id = customer_id
        self._session_id = session_id
        self._payment_id = payment_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body20':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_20 of this Body20.  # noqa: E501
        :rtype: Body20
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body20.


        :return: The token of this Body20.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body20.


        :param token: The token of this Body20.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def reference(self) -> str:
        """Gets the reference of this Body20.


        :return: The reference of this Body20.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Body20.


        :param reference: The reference of this Body20.
        :type reference: str
        """

        self._reference = reference

    @property
    def customer_id(self) -> str:
        """Gets the customer_id of this Body20.


        :return: The customer_id of this Body20.
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: str):
        """Sets the customer_id of this Body20.


        :param customer_id: The customer_id of this Body20.
        :type customer_id: str
        """

        self._customer_id = customer_id

    @property
    def session_id(self) -> str:
        """Gets the session_id of this Body20.


        :return: The session_id of this Body20.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this Body20.


        :param session_id: The session_id of this Body20.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def payment_id(self) -> str:
        """Gets the payment_id of this Body20.


        :return: The payment_id of this Body20.
        :rtype: str
        """
        return self._payment_id

    @payment_id.setter
    def payment_id(self, payment_id: str):
        """Sets the payment_id of this Body20.


        :param payment_id: The payment_id of this Body20.
        :type payment_id: str
        """

        self._payment_id = payment_id
