# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body27(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, reference: str=None, request_id: str=None):  # noqa: E501
        """Body27 - a model defined in Swagger

        :param token: The token of this Body27.  # noqa: E501
        :type token: str
        :param reference: The reference of this Body27.  # noqa: E501
        :type reference: str
        :param request_id: The request_id of this Body27.  # noqa: E501
        :type request_id: str
        """
        self.swagger_types = {
            'token': str,
            'reference': str,
            'request_id': str
        }

        self.attribute_map = {
            'token': 'token',
            'reference': 'reference',
            'request_id': 'request_id'
        }
        self._token = token
        self._reference = reference
        self._request_id = request_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body27':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_27 of this Body27.  # noqa: E501
        :rtype: Body27
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body27.


        :return: The token of this Body27.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body27.


        :param token: The token of this Body27.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def reference(self) -> str:
        """Gets the reference of this Body27.


        :return: The reference of this Body27.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Body27.


        :param reference: The reference of this Body27.
        :type reference: str
        """

        self._reference = reference

    @property
    def request_id(self) -> str:
        """Gets the request_id of this Body27.


        :return: The request_id of this Body27.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: str):
        """Sets the request_id of this Body27.


        :param request_id: The request_id of this Body27.
        :type request_id: str
        """

        self._request_id = request_id
