# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body30(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, session_id: str=None, package_id: str=None, number_of_days: str=None):  # noqa: E501
        """Body30 - a model defined in Swagger

        :param token: The token of this Body30.  # noqa: E501
        :type token: str
        :param session_id: The session_id of this Body30.  # noqa: E501
        :type session_id: str
        :param package_id: The package_id of this Body30.  # noqa: E501
        :type package_id: str
        :param number_of_days: The number_of_days of this Body30.  # noqa: E501
        :type number_of_days: str
        """
        self.swagger_types = {
            'token': str,
            'session_id': str,
            'package_id': str,
            'number_of_days': str
        }

        self.attribute_map = {
            'token': 'token',
            'session_id': 'session_id',
            'package_id': 'package_id',
            'number_of_days': 'number_of_days'
        }
        self._token = token
        self._session_id = session_id
        self._package_id = package_id
        self._number_of_days = number_of_days

    @classmethod
    def from_dict(cls, dikt) -> 'Body30':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_30 of this Body30.  # noqa: E501
        :rtype: Body30
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body30.


        :return: The token of this Body30.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body30.


        :param token: The token of this Body30.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def session_id(self) -> str:
        """Gets the session_id of this Body30.


        :return: The session_id of this Body30.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this Body30.


        :param session_id: The session_id of this Body30.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def package_id(self) -> str:
        """Gets the package_id of this Body30.


        :return: The package_id of this Body30.
        :rtype: str
        """
        return self._package_id

    @package_id.setter
    def package_id(self, package_id: str):
        """Sets the package_id of this Body30.


        :param package_id: The package_id of this Body30.
        :type package_id: str
        """

        self._package_id = package_id

    @property
    def number_of_days(self) -> str:
        """Gets the number_of_days of this Body30.


        :return: The number_of_days of this Body30.
        :rtype: str
        """
        return self._number_of_days

    @number_of_days.setter
    def number_of_days(self, number_of_days: str):
        """Sets the number_of_days of this Body30.


        :param number_of_days: The number_of_days of this Body30.
        :type number_of_days: str
        """

        self._number_of_days = number_of_days
