# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body7(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, full_name: str=None, amount: int=None, mobile_number: str=None, reference: str=None):  # noqa: E501
        """Body7 - a model defined in Swagger

        :param token: The token of this Body7.  # noqa: E501
        :type token: str
        :param full_name: The full_name of this Body7.  # noqa: E501
        :type full_name: str
        :param amount: The amount of this Body7.  # noqa: E501
        :type amount: int
        :param mobile_number: The mobile_number of this Body7.  # noqa: E501
        :type mobile_number: str
        :param reference: The reference of this Body7.  # noqa: E501
        :type reference: str
        """
        self.swagger_types = {
            'token': str,
            'full_name': str,
            'amount': int,
            'mobile_number': str,
            'reference': str
        }

        self.attribute_map = {
            'token': 'token',
            'full_name': 'full_name',
            'amount': 'amount',
            'mobile_number': 'mobile_number',
            'reference': 'reference'
        }
        self._token = token
        self._full_name = full_name
        self._amount = amount
        self._mobile_number = mobile_number
        self._reference = reference

    @classmethod
    def from_dict(cls, dikt) -> 'Body7':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_7 of this Body7.  # noqa: E501
        :rtype: Body7
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body7.


        :return: The token of this Body7.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body7.


        :param token: The token of this Body7.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def full_name(self) -> str:
        """Gets the full_name of this Body7.


        :return: The full_name of this Body7.
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name: str):
        """Sets the full_name of this Body7.


        :param full_name: The full_name of this Body7.
        :type full_name: str
        """

        self._full_name = full_name

    @property
    def amount(self) -> int:
        """Gets the amount of this Body7.


        :return: The amount of this Body7.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this Body7.


        :param amount: The amount of this Body7.
        :type amount: int
        """

        self._amount = amount

    @property
    def mobile_number(self) -> str:
        """Gets the mobile_number of this Body7.


        :return: The mobile_number of this Body7.
        :rtype: str
        """
        return self._mobile_number

    @mobile_number.setter
    def mobile_number(self, mobile_number: str):
        """Sets the mobile_number of this Body7.


        :param mobile_number: The mobile_number of this Body7.
        :type mobile_number: str
        """

        self._mobile_number = mobile_number

    @property
    def reference(self) -> str:
        """Gets the reference of this Body7.


        :return: The reference of this Body7.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Body7.


        :param reference: The reference of this Body7.
        :type reference: str
        """

        self._reference = reference
