# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body48(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, show_id: str=None):  # noqa: E501
        """Body48 - a model defined in Swagger

        :param token: The token of this Body48.  # noqa: E501
        :type token: str
        :param show_id: The show_id of this Body48.  # noqa: E501
        :type show_id: str
        """
        self.swagger_types = {
            'token': str,
            'show_id': str
        }

        self.attribute_map = {
            'token': 'token',
            'show_id': 'show_id'
        }
        self._token = token
        self._show_id = show_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body48':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_48 of this Body48.  # noqa: E501
        :rtype: Body48
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body48.


        :return: The token of this Body48.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body48.


        :param token: The token of this Body48.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def show_id(self) -> str:
        """Gets the show_id of this Body48.


        :return: The show_id of this Body48.
        :rtype: str
        """
        return self._show_id

    @show_id.setter
    def show_id(self, show_id: str):
        """Sets the show_id of this Body48.


        :param show_id: The show_id of this Body48.
        :type show_id: str
        """

        self._show_id = show_id
