# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body40(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, reference: str=None, amount: int=None, policy_no: str=None, transaction_id: str=None):  # noqa: E501
        """Body40 - a model defined in Swagger

        :param token: The token of this Body40.  # noqa: E501
        :type token: str
        :param reference: The reference of this Body40.  # noqa: E501
        :type reference: str
        :param amount: The amount of this Body40.  # noqa: E501
        :type amount: int
        :param policy_no: The policy_no of this Body40.  # noqa: E501
        :type policy_no: str
        :param transaction_id: The transaction_id of this Body40.  # noqa: E501
        :type transaction_id: str
        """
        self.swagger_types = {
            'token': str,
            'reference': str,
            'amount': int,
            'policy_no': str,
            'transaction_id': str
        }

        self.attribute_map = {
            'token': 'token',
            'reference': 'reference',
            'amount': 'amount',
            'policy_no': 'policy_no',
            'transaction_id': 'transaction_id'
        }
        self._token = token
        self._reference = reference
        self._amount = amount
        self._policy_no = policy_no
        self._transaction_id = transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body40':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_40 of this Body40.  # noqa: E501
        :rtype: Body40
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body40.


        :return: The token of this Body40.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body40.


        :param token: The token of this Body40.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def reference(self) -> str:
        """Gets the reference of this Body40.


        :return: The reference of this Body40.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Body40.


        :param reference: The reference of this Body40.
        :type reference: str
        """

        self._reference = reference

    @property
    def amount(self) -> int:
        """Gets the amount of this Body40.


        :return: The amount of this Body40.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this Body40.


        :param amount: The amount of this Body40.
        :type amount: int
        """

        self._amount = amount

    @property
    def policy_no(self) -> str:
        """Gets the policy_no of this Body40.


        :return: The policy_no of this Body40.
        :rtype: str
        """
        return self._policy_no

    @policy_no.setter
    def policy_no(self, policy_no: str):
        """Sets the policy_no of this Body40.


        :param policy_no: The policy_no of this Body40.
        :type policy_no: str
        """

        self._policy_no = policy_no

    @property
    def transaction_id(self) -> str:
        """Gets the transaction_id of this Body40.


        :return: The transaction_id of this Body40.
        :rtype: str
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id: str):
        """Sets the transaction_id of this Body40.


        :param transaction_id: The transaction_id of this Body40.
        :type transaction_id: str
        """

        self._transaction_id = transaction_id
