# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body36(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, session_id: str=None, amount: int=None):  # noqa: E501
        """Body36 - a model defined in Swagger

        :param token: The token of this Body36.  # noqa: E501
        :type token: str
        :param session_id: The session_id of this Body36.  # noqa: E501
        :type session_id: str
        :param amount: The amount of this Body36.  # noqa: E501
        :type amount: int
        """
        self.swagger_types = {
            'token': str,
            'session_id': str,
            'amount': int
        }

        self.attribute_map = {
            'token': 'token',
            'session_id': 'session_id',
            'amount': 'amount'
        }
        self._token = token
        self._session_id = session_id
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'Body36':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_36 of this Body36.  # noqa: E501
        :rtype: Body36
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body36.


        :return: The token of this Body36.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body36.


        :param token: The token of this Body36.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def session_id(self) -> str:
        """Gets the session_id of this Body36.


        :return: The session_id of this Body36.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this Body36.


        :param session_id: The session_id of this Body36.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def amount(self) -> int:
        """Gets the amount of this Body36.


        :return: The amount of this Body36.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this Body36.


        :param amount: The amount of this Body36.
        :type amount: int
        """

        self._amount = amount
