# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body47(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, cancel_tickets: str=None, booking_id: str=None):  # noqa: E501
        """Body47 - a model defined in Swagger

        :param token: The token of this Body47.  # noqa: E501
        :type token: str
        :param cancel_tickets: The cancel_tickets of this Body47.  # noqa: E501
        :type cancel_tickets: str
        :param booking_id: The booking_id of this Body47.  # noqa: E501
        :type booking_id: str
        """
        self.swagger_types = {
            'token': str,
            'cancel_tickets': str,
            'booking_id': str
        }

        self.attribute_map = {
            'token': 'token',
            'cancel_tickets': 'cancel_tickets',
            'booking_id': 'booking_id'
        }
        self._token = token
        self._cancel_tickets = cancel_tickets
        self._booking_id = booking_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body47':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_47 of this Body47.  # noqa: E501
        :rtype: Body47
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body47.


        :return: The token of this Body47.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body47.


        :param token: The token of this Body47.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def cancel_tickets(self) -> str:
        """Gets the cancel_tickets of this Body47.


        :return: The cancel_tickets of this Body47.
        :rtype: str
        """
        return self._cancel_tickets

    @cancel_tickets.setter
    def cancel_tickets(self, cancel_tickets: str):
        """Sets the cancel_tickets of this Body47.


        :param cancel_tickets: The cancel_tickets of this Body47.
        :type cancel_tickets: str
        """

        self._cancel_tickets = cancel_tickets

    @property
    def booking_id(self) -> str:
        """Gets the booking_id of this Body47.


        :return: The booking_id of this Body47.
        :rtype: str
        """
        return self._booking_id

    @booking_id.setter
    def booking_id(self, booking_id: str):
        """Sets the booking_id of this Body47.


        :param booking_id: The booking_id of this Body47.
        :type booking_id: str
        """

        self._booking_id = booking_id
