# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body15(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, reference: str=None, smartcard_id: str=None):  # noqa: E501
        """Body15 - a model defined in Swagger

        :param token: The token of this Body15.  # noqa: E501
        :type token: str
        :param reference: The reference of this Body15.  # noqa: E501
        :type reference: str
        :param smartcard_id: The smartcard_id of this Body15.  # noqa: E501
        :type smartcard_id: str
        """
        self.swagger_types = {
            'token': str,
            'reference': str,
            'smartcard_id': str
        }

        self.attribute_map = {
            'token': 'token',
            'reference': 'reference',
            'smartcard_id': 'smartcard_id'
        }
        self._token = token
        self._reference = reference
        self._smartcard_id = smartcard_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body15':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_15 of this Body15.  # noqa: E501
        :rtype: Body15
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body15.


        :return: The token of this Body15.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body15.


        :param token: The token of this Body15.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def reference(self) -> str:
        """Gets the reference of this Body15.


        :return: The reference of this Body15.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Body15.


        :param reference: The reference of this Body15.
        :type reference: str
        """

        self._reference = reference

    @property
    def smartcard_id(self) -> str:
        """Gets the smartcard_id of this Body15.


        :return: The smartcard_id of this Body15.
        :rtype: str
        """
        return self._smartcard_id

    @smartcard_id.setter
    def smartcard_id(self, smartcard_id: str):
        """Sets the smartcard_id of this Body15.


        :param smartcard_id: The smartcard_id of this Body15.
        :type smartcard_id: str
        """

        self._smartcard_id = smartcard_id
