# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body25(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, reference: str=None, customer_id: str=None, stbusername: str=None, service: str=None):  # noqa: E501
        """Body25 - a model defined in Swagger

        :param token: The token of this Body25.  # noqa: E501
        :type token: str
        :param reference: The reference of this Body25.  # noqa: E501
        :type reference: str
        :param customer_id: The customer_id of this Body25.  # noqa: E501
        :type customer_id: str
        :param stbusername: The stbusername of this Body25.  # noqa: E501
        :type stbusername: str
        :param service: The service of this Body25.  # noqa: E501
        :type service: str
        """
        self.swagger_types = {
            'token': str,
            'reference': str,
            'customer_id': str,
            'stbusername': str,
            'service': str
        }

        self.attribute_map = {
            'token': 'token',
            'reference': 'reference',
            'customer_id': 'customer_id',
            'stbusername': 'stb/username',
            'service': 'service'
        }
        self._token = token
        self._reference = reference
        self._customer_id = customer_id
        self._stbusername = stbusername
        self._service = service

    @classmethod
    def from_dict(cls, dikt) -> 'Body25':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_25 of this Body25.  # noqa: E501
        :rtype: Body25
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body25.


        :return: The token of this Body25.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body25.


        :param token: The token of this Body25.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def reference(self) -> str:
        """Gets the reference of this Body25.


        :return: The reference of this Body25.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Body25.


        :param reference: The reference of this Body25.
        :type reference: str
        """

        self._reference = reference

    @property
    def customer_id(self) -> str:
        """Gets the customer_id of this Body25.


        :return: The customer_id of this Body25.
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: str):
        """Sets the customer_id of this Body25.


        :param customer_id: The customer_id of this Body25.
        :type customer_id: str
        """

        self._customer_id = customer_id

    @property
    def stbusername(self) -> str:
        """Gets the stbusername of this Body25.


        :return: The stbusername of this Body25.
        :rtype: str
        """
        return self._stbusername

    @stbusername.setter
    def stbusername(self, stbusername: str):
        """Sets the stbusername of this Body25.


        :param stbusername: The stbusername of this Body25.
        :type stbusername: str
        """

        self._stbusername = stbusername

    @property
    def service(self) -> str:
        """Gets the service of this Body25.


        :return: The service of this Body25.
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service: str):
        """Sets the service of this Body25.


        :param service: The service of this Body25.
        :type service: str
        """

        self._service = service
