# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body24(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, reference: str=None, username: str=None, amount: int=None, duration: str=None):  # noqa: E501
        """Body24 - a model defined in Swagger

        :param token: The token of this Body24.  # noqa: E501
        :type token: str
        :param reference: The reference of this Body24.  # noqa: E501
        :type reference: str
        :param username: The username of this Body24.  # noqa: E501
        :type username: str
        :param amount: The amount of this Body24.  # noqa: E501
        :type amount: int
        :param duration: The duration of this Body24.  # noqa: E501
        :type duration: str
        """
        self.swagger_types = {
            'token': str,
            'reference': str,
            'username': str,
            'amount': int,
            'duration': str
        }

        self.attribute_map = {
            'token': 'token',
            'reference': 'reference',
            'username': 'username',
            'amount': 'amount',
            'duration': 'duration'
        }
        self._token = token
        self._reference = reference
        self._username = username
        self._amount = amount
        self._duration = duration

    @classmethod
    def from_dict(cls, dikt) -> 'Body24':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_24 of this Body24.  # noqa: E501
        :rtype: Body24
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body24.


        :return: The token of this Body24.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body24.


        :param token: The token of this Body24.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def reference(self) -> str:
        """Gets the reference of this Body24.


        :return: The reference of this Body24.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Body24.


        :param reference: The reference of this Body24.
        :type reference: str
        """

        self._reference = reference

    @property
    def username(self) -> str:
        """Gets the username of this Body24.


        :return: The username of this Body24.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Body24.


        :param username: The username of this Body24.
        :type username: str
        """

        self._username = username

    @property
    def amount(self) -> int:
        """Gets the amount of this Body24.


        :return: The amount of this Body24.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this Body24.


        :param amount: The amount of this Body24.
        :type amount: int
        """

        self._amount = amount

    @property
    def duration(self) -> str:
        """Gets the duration of this Body24.


        :return: The duration of this Body24.
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration: str):
        """Sets the duration of this Body24.


        :param duration: The duration of this Body24.
        :type duration: str
        """

        self._duration = duration
