# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body23(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, username: str=None):  # noqa: E501
        """Body23 - a model defined in Swagger

        :param token: The token of this Body23.  # noqa: E501
        :type token: str
        :param username: The username of this Body23.  # noqa: E501
        :type username: str
        """
        self.swagger_types = {
            'token': str,
            'username': str
        }

        self.attribute_map = {
            'token': 'token',
            'username': 'username'
        }
        self._token = token
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'Body23':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_23 of this Body23.  # noqa: E501
        :rtype: Body23
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body23.


        :return: The token of this Body23.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body23.


        :param token: The token of this Body23.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def username(self) -> str:
        """Gets the username of this Body23.


        :return: The username of this Body23.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Body23.


        :param username: The username of this Body23.
        :type username: str
        """

        self._username = username
