# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body3(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, reference: str=None, amount: int=None, username: str=None, number: str=None, address: str=None):  # noqa: E501
        """Body3 - a model defined in Swagger

        :param token: The token of this Body3.  # noqa: E501
        :type token: str
        :param reference: The reference of this Body3.  # noqa: E501
        :type reference: str
        :param amount: The amount of this Body3.  # noqa: E501
        :type amount: int
        :param username: The username of this Body3.  # noqa: E501
        :type username: str
        :param number: The number of this Body3.  # noqa: E501
        :type number: str
        :param address: The address of this Body3.  # noqa: E501
        :type address: str
        """
        self.swagger_types = {
            'token': str,
            'reference': str,
            'amount': int,
            'username': str,
            'number': str,
            'address': str
        }

        self.attribute_map = {
            'token': 'token',
            'reference': 'reference',
            'amount': 'amount',
            'username': 'username',
            'number': 'number',
            'address': 'address'
        }
        self._token = token
        self._reference = reference
        self._amount = amount
        self._username = username
        self._number = number
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'Body3':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_3 of this Body3.  # noqa: E501
        :rtype: Body3
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body3.


        :return: The token of this Body3.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body3.


        :param token: The token of this Body3.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def reference(self) -> str:
        """Gets the reference of this Body3.


        :return: The reference of this Body3.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Body3.


        :param reference: The reference of this Body3.
        :type reference: str
        """

        self._reference = reference

    @property
    def amount(self) -> int:
        """Gets the amount of this Body3.


        :return: The amount of this Body3.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this Body3.


        :param amount: The amount of this Body3.
        :type amount: int
        """

        self._amount = amount

    @property
    def username(self) -> str:
        """Gets the username of this Body3.


        :return: The username of this Body3.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Body3.


        :param username: The username of this Body3.
        :type username: str
        """

        self._username = username

    @property
    def number(self) -> str:
        """Gets the number of this Body3.


        :return: The number of this Body3.
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number: str):
        """Sets the number of this Body3.


        :param number: The number of this Body3.
        :type number: str
        """

        self._number = number

    @property
    def address(self) -> str:
        """Gets the address of this Body3.


        :return: The address of this Body3.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this Body3.


        :param address: The address of this Body3.
        :type address: str
        """

        self._address = address
