# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body4(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, reference: str=None, amount: int=None, username: str=None, number: str=None):  # noqa: E501
        """Body4 - a model defined in Swagger

        :param token: The token of this Body4.  # noqa: E501
        :type token: str
        :param reference: The reference of this Body4.  # noqa: E501
        :type reference: str
        :param amount: The amount of this Body4.  # noqa: E501
        :type amount: int
        :param username: The username of this Body4.  # noqa: E501
        :type username: str
        :param number: The number of this Body4.  # noqa: E501
        :type number: str
        """
        self.swagger_types = {
            'token': str,
            'reference': str,
            'amount': int,
            'username': str,
            'number': str
        }

        self.attribute_map = {
            'token': 'token',
            'reference': 'reference',
            'amount': 'amount',
            'username': 'username',
            'number': 'number'
        }
        self._token = token
        self._reference = reference
        self._amount = amount
        self._username = username
        self._number = number

    @classmethod
    def from_dict(cls, dikt) -> 'Body4':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_4 of this Body4.  # noqa: E501
        :rtype: Body4
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body4.


        :return: The token of this Body4.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body4.


        :param token: The token of this Body4.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def reference(self) -> str:
        """Gets the reference of this Body4.


        :return: The reference of this Body4.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Body4.


        :param reference: The reference of this Body4.
        :type reference: str
        """

        self._reference = reference

    @property
    def amount(self) -> int:
        """Gets the amount of this Body4.


        :return: The amount of this Body4.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this Body4.


        :param amount: The amount of this Body4.
        :type amount: int
        """

        self._amount = amount

    @property
    def username(self) -> str:
        """Gets the username of this Body4.


        :return: The username of this Body4.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Body4.


        :param username: The username of this Body4.
        :type username: str
        """

        self._username = username

    @property
    def number(self) -> str:
        """Gets the number of this Body4.


        :return: The number of this Body4.
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number: str):
        """Sets the number of this Body4.


        :param number: The number of this Body4.
        :type number: str
        """

        self._number = number
