# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body49(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, reference: str=None, show_id: str=None, ticket_type_id: str=None, old_session_id: str=None):  # noqa: E501
        """Body49 - a model defined in Swagger

        :param token: The token of this Body49.  # noqa: E501
        :type token: str
        :param reference: The reference of this Body49.  # noqa: E501
        :type reference: str
        :param show_id: The show_id of this Body49.  # noqa: E501
        :type show_id: str
        :param ticket_type_id: The ticket_type_id of this Body49.  # noqa: E501
        :type ticket_type_id: str
        :param old_session_id: The old_session_id of this Body49.  # noqa: E501
        :type old_session_id: str
        """
        self.swagger_types = {
            'token': str,
            'reference': str,
            'show_id': str,
            'ticket_type_id': str,
            'old_session_id': str
        }

        self.attribute_map = {
            'token': 'token',
            'reference': 'reference',
            'show_id': 'show_id',
            'ticket_type_id': 'ticket_type_id',
            'old_session_id': 'old_session_id'
        }
        self._token = token
        self._reference = reference
        self._show_id = show_id
        self._ticket_type_id = ticket_type_id
        self._old_session_id = old_session_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body49':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_49 of this Body49.  # noqa: E501
        :rtype: Body49
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body49.


        :return: The token of this Body49.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body49.


        :param token: The token of this Body49.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def reference(self) -> str:
        """Gets the reference of this Body49.


        :return: The reference of this Body49.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Body49.


        :param reference: The reference of this Body49.
        :type reference: str
        """

        self._reference = reference

    @property
    def show_id(self) -> str:
        """Gets the show_id of this Body49.


        :return: The show_id of this Body49.
        :rtype: str
        """
        return self._show_id

    @show_id.setter
    def show_id(self, show_id: str):
        """Sets the show_id of this Body49.


        :param show_id: The show_id of this Body49.
        :type show_id: str
        """

        self._show_id = show_id

    @property
    def ticket_type_id(self) -> str:
        """Gets the ticket_type_id of this Body49.


        :return: The ticket_type_id of this Body49.
        :rtype: str
        """
        return self._ticket_type_id

    @ticket_type_id.setter
    def ticket_type_id(self, ticket_type_id: str):
        """Sets the ticket_type_id of this Body49.


        :param ticket_type_id: The ticket_type_id of this Body49.
        :type ticket_type_id: str
        """

        self._ticket_type_id = ticket_type_id

    @property
    def old_session_id(self) -> str:
        """Gets the old_session_id of this Body49.


        :return: The old_session_id of this Body49.
        :rtype: str
        """
        return self._old_session_id

    @old_session_id.setter
    def old_session_id(self, old_session_id: str):
        """Sets the old_session_id of this Body49.


        :param old_session_id: The old_session_id of this Body49.
        :type old_session_id: str
        """

        self._old_session_id = old_session_id
