# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body26(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, session_id: str=None, amount: int=None, code: str=None, service: str=None):  # noqa: E501
        """Body26 - a model defined in Swagger

        :param token: The token of this Body26.  # noqa: E501
        :type token: str
        :param session_id: The session_id of this Body26.  # noqa: E501
        :type session_id: str
        :param amount: The amount of this Body26.  # noqa: E501
        :type amount: int
        :param code: The code of this Body26.  # noqa: E501
        :type code: str
        :param service: The service of this Body26.  # noqa: E501
        :type service: str
        """
        self.swagger_types = {
            'token': str,
            'session_id': str,
            'amount': int,
            'code': str,
            'service': str
        }

        self.attribute_map = {
            'token': 'token',
            'session_id': 'session_id',
            'amount': 'amount',
            'code': 'code',
            'service': 'service'
        }
        self._token = token
        self._session_id = session_id
        self._amount = amount
        self._code = code
        self._service = service

    @classmethod
    def from_dict(cls, dikt) -> 'Body26':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_26 of this Body26.  # noqa: E501
        :rtype: Body26
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Body26.


        :return: The token of this Body26.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Body26.


        :param token: The token of this Body26.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def session_id(self) -> str:
        """Gets the session_id of this Body26.


        :return: The session_id of this Body26.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this Body26.


        :param session_id: The session_id of this Body26.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def amount(self) -> int:
        """Gets the amount of this Body26.


        :return: The amount of this Body26.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this Body26.


        :param amount: The amount of this Body26.
        :type amount: int
        """

        self._amount = amount

    @property
    def code(self) -> str:
        """Gets the code of this Body26.


        :return: The code of this Body26.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this Body26.


        :param code: The code of this Body26.
        :type code: str
        """

        self._code = code

    @property
    def service(self) -> str:
        """Gets the service of this Body26.


        :return: The service of this Body26.
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service: str):
        """Sets the service of this Body26.


        :param service: The service of this Body26.
        :type service: str
        """

        self._service = service
