# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Network(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, username: str=None, mobile_number: str=None, amount: int=None, reference: str=None):  # noqa: E501
        """Network - a model defined in Swagger

        :param token: The token of this Network.  # noqa: E501
        :type token: str
        :param username: The username of this Network.  # noqa: E501
        :type username: str
        :param mobile_number: The mobile_number of this Network.  # noqa: E501
        :type mobile_number: str
        :param amount: The amount of this Network.  # noqa: E501
        :type amount: int
        :param reference: The reference of this Network.  # noqa: E501
        :type reference: str
        """
        self.swagger_types = {
            'token': str,
            'username': str,
            'mobile_number': str,
            'amount': int,
            'reference': str
        }

        self.attribute_map = {
            'token': 'token',
            'username': 'username',
            'mobile_number': 'mobile_number',
            'amount': 'amount',
            'reference': 'reference'
        }
        self._token = token
        self._username = username
        self._mobile_number = mobile_number
        self._amount = amount
        self._reference = reference

    @classmethod
    def from_dict(cls, dikt) -> 'Network':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Network of this Network.  # noqa: E501
        :rtype: Network
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this Network.


        :return: The token of this Network.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this Network.


        :param token: The token of this Network.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def username(self) -> str:
        """Gets the username of this Network.


        :return: The username of this Network.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Network.


        :param username: The username of this Network.
        :type username: str
        """

        self._username = username

    @property
    def mobile_number(self) -> str:
        """Gets the mobile_number of this Network.


        :return: The mobile_number of this Network.
        :rtype: str
        """
        return self._mobile_number

    @mobile_number.setter
    def mobile_number(self, mobile_number: str):
        """Sets the mobile_number of this Network.


        :param mobile_number: The mobile_number of this Network.
        :type mobile_number: str
        """

        self._mobile_number = mobile_number

    @property
    def amount(self) -> int:
        """Gets the amount of this Network.


        :return: The amount of this Network.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this Network.


        :param amount: The amount of this Network.
        :type amount: int
        """

        self._amount = amount

    @property
    def reference(self) -> str:
        """Gets the reference of this Network.


        :return: The reference of this Network.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this Network.


        :param reference: The reference of this Network.
        :type reference: str
        """

        self._reference = reference
